### ISSUE TITLE
scikit-sparse issue when running deconvolution

### ISSUE THREAD

**Issue by andres-ocampo1** [tansey-lab/bayestme#135]
Hi!
Thank you so much for sharing this method! I have been following the example workflow on the documentation. After I pulled bayestme from docker, I was able to successfully run steps 1-4 (loading the spaceranger data, filtering the genes, and running/plotting the bleed correction. I decided to skip step 5 for now and jump to step 6. However, I am having issues with step 6 (Run deconvolution using deconvolve command). When I run the deconvolution command I get the following error:

`Traceback (most recent call last):
  File "...file path.../fast_multivariate_normal.py", line 9, in <module>
    from sksparse.cholmod import cholesky, CholmodNotPositiveDefiniteError
ModuleNotFoundError: No module named 'sksparse'`

Do you have any suggestions on how I can fix this?

Thank you!

**Comment by andres-ocampo1** [comment]
Hi Jeff, 

Thank you for your quick reply. Per your suggestion, I went through the installation steps for nextflow. With that being said, I am having some trouble understanding the documentation. I cloned the repo and ran the following command `nextflow run main.nf -profile docker --input $IPATH/Thy1/outs --n_cell_types 8 --outdir $IPATH/processed/Thy1_Processed/nextflow_bayes` and got the following errors:

```
| => nextflow run main.nf -profile docker --input $IPATH/Thy1/outs --n_cell_types 8 --outdir $IPATH/processed/Thy1_Processed/nextflow_bayes

Nextflow 23.10.1 is available - Please consider updating your version to it
N E X T F L O W  ~  version 23.10.0
Launching `main.nf` [hopeful_galileo] DSL2 - revision: c57728ecca
   ### ERROR ###   Max cpus '[:]' is not valid! Using default value: 1
executor >  local (1)
[b5/0624f6] process > BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_LOAD_SPACERANGER (sample) [  0%] 0 of 1
[-        ] process > BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_FILTER_GENES              -
[-        ] process > BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_DECONVOLUTION             -

ERROR ~ Error executing process > 'BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_LOAD_SPACERANGER (sample)'

Caused by:
  Process `BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_LOAD_SPACERANGER (sample)` terminated with an error exit status (1)

Command executed:

  mkdir "sample"
  load_spaceranger --input outs         --output "sample/dataset.h5ad"         
executor >  local (1)
[b5/0624f6] process > BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_LOAD_SPACERANGER (sample) [100%] 1 of 1, failed: 1 ✘
[-        ] process > BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_FILTER_GENES              -
[-        ] process > BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_DECONVOLUTION             -
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_LOAD_SPACERANGER (sample)'

Caused by:
  Process `BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_LOAD_SPACERANGER (sample)` terminated with an error exit status (1)

Command executed:

  mkdir "sample"
  load_spaceranger --input outs         --output "sample/dataset.h5ad"         
executor >  local (1)
[b5/0624f6] process > BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_LOAD_SPACERANGER (sample) [100%] 1 of 1, failed: 1 ✘
[-        ] process > BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_FILTER_GENES              -
[-        ] process > BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_DECONVOLUTION             -
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_LOAD_SPACERANGER (sample)'

Caused by:
  Process `BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_LOAD_SPACERANGER (sample)` terminated with an error exit status (1)

Command executed:

  mkdir "sample"
  load_spaceranger --input outs         --output "sample/dataset.h5ad"         
  
  cat <<-END_VERSIONS > versions.yml
  "BAYESTME_BASIC_VISIUM_ANALYSIS:BAYESTME_LOAD_SPACERANGER":
      bayestme: $( python -c 'from importlib.metadata import version;print(version("bayestme"))' )
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
  2024-01-14 03:27:57,638 - bayestme.data - INFO - detected 4991 spots, 36945 genes
  Traceback (most recent call last):
    File "/usr/local/bin/load_spaceranger", line 8, in <module>
      sys.exit(main())
               ^^^^^^
    File "/usr/local/lib/python3.11/site-packages/bayestme/cli/load_spaceranger.py", line 30, in main
      dataset = data.SpatialExpressionDataset.read_spaceranger(args.input)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/bayestme/data.py", line 279, in read_spaceranger
      positions = positions_df.loc[barcodes[0]][
                  ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/indexing.py", line 1153, in __getitem__
      return self._getitem_axis(maybe_callable, axis=axis)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/indexing.py", line 1382, in _getitem_axis
      return self._getitem_iterable(key, axis=axis)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/indexing.py", line 1322, in _getitem_iterable
      keyarr, indexer = self._get_listlike_indexer(key, axis)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/indexing.py", line 1520, in _get_listlike_indexer
      keyarr, indexer = ax._get_indexer_strict(key, axis_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6115, in _get_indexer_strict
      self._raise_if_missing(keyarr, indexer, axis_name)
    File "/usr/local/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 6179, in _raise_if_missing
      raise KeyError(f"{not_found} not in index")
  KeyError: "['ACGCCTGACACGCGCT-1'] not in index"

Work dir:
  /Users/aocam/git-repos/bayestme/work/b5/0624f69a75bc8700349c1631e630f3

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
```



My goal is to just run through the example workflow steps with my data (skipping step 5). What nextflow command would I need to run in order to do that?

Thank you so much for your help!

**Comment by andres-ocampo1** [comment]
This is what my poitions.csv file looks like:
![image](https://github.com/tansey-lab/bayestme/assets/98126322/135e4183-6ea8-48a4-9c4f-3e45d270bf4b)

**Comment by andres-ocampo1** [comment]
I did also try it with a different dataset that did have a header row that looks like this:
<img width="415" alt="image" src="https://github.com/tansey-lab/bayestme/assets/98126322/a9ac7acd-1f5f-4ebc-a9b7-c060581570cf">
However, I got the same error.
