### ISSUE TITLE
Cannot have number of splits n_splits=15 greater than the number of samples: n_samples=2.

### ISSUE THREAD

**Issue by JihyunKiminGithub** [tansey-lab/bayestme#174]
Dear author,

When I ran this code,

```
Apptainer> phenotype_selection --adata ./EGS-19-D2-5p/EGS_19_D2_5p_filtered.h5ad --job-index 1 --n-fold 5 --n-splits 10 --n-components-min 2 --n-components-max 12 \
--output-dir EGS_19_D2_5p --seed 2024 --n-components 5 --n-samples 10 --expression-truth None -v

```
I got this error,

```
Apptainer> phenotype_selection --adata ./EGS-19-D2-5p/EGS_19_D2_5p_filtered.h5ad --job-index 1 --n-fold 5 --n-splits 10 --n-components-min 2 --n-components-max 12 \
--output-dir EGS_19_D2_5p --seed 2024 --n-components 5 --n-samples 10 --expression-truth None -v
2024-04-30 08:51:20,399 - bayestme.cli.phenotype_selection - INFO - phenotype_selection called with arguments: Namespace(adata='./EGS-19-D2-5p/EGS_19_D2_5p_filtered.h5ad', job_index=1, n_fold=5, n_splits=10, n_components_min=2, n_components_max=12, spatial_smoothing_values=None, output_dir='EGS_19_D2_5p', seed=2024, n_components=5, spatial_smoothing_parameter=None, n_samples=10, expression_truth=['None'], n_svi_steps=10000, use_spatial_guide=True, verbose=True)
Traceback (most recent call last):
  File "/usr/local/bin/phenotype_selection", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bayestme/cli/phenotype_selection.py", line 83, in main
    all_jobs = [
               ^
  File "/usr/local/lib/python3.11/site-packages/bayestme/cli/phenotype_selection.py", line 83, in <listcomp>
    all_jobs = [
               ^
  File "/usr/local/lib/python3.11/site-packages/bayestme/phenotype_selection.py", line 105, in get_phenotype_selection_parameters_for_folds
    for fold_number, mask in enumerate(
  File "/usr/local/lib/python3.11/site-packages/bayestme/phenotype_selection.py", line 50, in create_folds
    _, heldout = next(splits)
                 ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 370, in split
    raise ValueError(
ValueError: Cannot have number of splits n_splits=10 greater than the number of samples: n_samples=2.


```

Since I set  --n-splits 10 --n-samples 10, I don't understand why those errors pop up!

Thank you in advance,
Jihyun

**Comment by JihyunKiminGithub** [comment]
Thank you for updating me on the current situation.
I believe Bayestme is an excellent tool and I'd like to incorporate it into my paper.
Could you please provide an estimate for when it will be fixed?

**Comment by JihyunKiminGithub** [comment]
Thank you, author.

When I ran the code, I got another error.

Apptainer> 
phenotype_selection --adata ./EGS-19-D2_HGD/EGS_19_D2_HGD_filtered.h5ad --job-index 1 --n-fold 5 --n-splits 10 --n-components-min 2 --n-components-max 12 \
--output-dir EGS_19_D2_HGD --seed 2024 --n-components 5 --n-samples 10 --expression-truth None -v
2024-05-01 13:06:31,192 - bayestme.cli.phenotype_selection - INFO - phenotype_selection called with arguments: Namespace(adata='./EGS-19-D2_HGD/EGS_19_D2_HGD_filtered.h5ad', job_index=1, n_fold=5, n_splits=10, n_components_min=2, n_components_max=12, spatial_smoothing_values=None, output_dir='EGS_19_D2_HGD', seed=2024, n_components=5, spatial_smoothing_parameter=None, n_samples=10, expression_truth=['None'], n_svi_steps=10000, use_spatial_guide=True, verbose=True)
Traceback (most recent call last):
  File "/usr/local/bin/phenotype_selection", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bayestme/cli/phenotype_selection.py", line 83, in main
    all_jobs = [
               ^
  File "/usr/local/lib/python3.11/site-packages/bayestme/cli/phenotype_selection.py", line 83, in <listcomp>
    all_jobs = [
               ^
  File "/usr/local/lib/python3.11/site-packages/bayestme/phenotype_selection.py", line 105, in get_phenotype_selection_parameters_for_folds
    for fold_number, mask in enumerate(
  File "/usr/local/lib/python3.11/site-packages/bayestme/phenotype_selection.py", line 50, in create_folds
    _, heldout = next(splits)
                 ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 370, in split
    raise ValueError(
ValueError: Cannot have number of splits n_splits=10 greater than the number of samples: n_samples=0.

**Comment by JihyunKiminGithub** [comment]
Thank you for your correction!
Please let me know if you have a chance to try and revise.
